integrations:
  - name: nr-win-eventlogs-app
    exec:
      - C:\Program Files\New Relic\newrelic-infra\custom-integrations\win-eventlogs.bat
    env:
      LOGNAME: Application
      EXCLLEVEL: none
      EXCLEVENTID: none
    working_dir: C:\Program Files\New Relic\newrelic-infra\custom-integrations\
    interval: 60s
  - name: nr-win-eventlogs-printservice
    exec:
      - C:\Program Files\New Relic\newrelic-infra\custom-integrations\win-eventlogs.bat
    env:
      LOGNAME: "Microsoft-Windows-PrintService/Admin"
      EXCLLEVEL: none
      EXCLEVENTID: none
    working_dir: C:\Program Files\New Relic\newrelic-infra\custom-integrations\
    interval: 60s
